SweetMoive/Areas/MovieUser/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net;
using SweetMoive.DAL.ModelManage;
using SweetMoive.DAL.Models;

namespace SweetMoive.Areas.MovieUser.Controllers
{
    public class CommentController : Controller
    {
        UserManage userManage = new UserManage();
        CommentManage commentMange = new CommentManage();
        LikeManage likeManage = new LikeManage();
        [HttpGet]
        public ActionResult CommentList(int? id,int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _comment = commentMange.FindList(p => p.MovieID == id);
            _comment=_comment.OrderBy(p => p.CommentTime);
            const int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(_comment.ToPagedList(pageNumber,pageSize));
        }
        //[HttpPost]
        //[UserAuthorize]
        //public ActionResult CommentLike(int)
        //{

        //    return Json(new { likestatus=1});
        //}
        [UserAuthorize]
        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult CommentSubmit([Bind(Include ="ID,Content,score,UserID,MovieID")] MovieComment comment)
        {
            comment.CommentTime = DateTime.Now;

            comment.User = userManage.Find(comment.UserID);
            int isUser=commentMange.Count(p => p.UserID == comment.UserID&&p.MovieID==comment.MovieID);
            if (isUser > 0)
            {
                return Content("<h1 class='text-center' style='color:#fff;'>您已评论过此电影!</h1>");
            }
            if (ModelState.IsValid)
            {
                commentMange.Add(comment);
                comment.User.SweetScore = comment.User.SweetScore++;
                userManage.Update(comment.User);
                var _comment = commentMange.FindList(p => p.MovieID == comment.MovieID);
                _comment = _comment.OrderBy(p => p.CommentTime);
                const int pageSize = 5;
                return PartialView("CommentList", _comment.ToPagedList(1, pageSize));
            }
            return Content("<h1 class='text-center' style='color:#fff;'>评论失败</h1>");
        }
    }
}

SweetMoive/Areas/MovieUser/Controllers/UserController.cs
using PagedList;
using SweetMoive.Areas.MovieUser.Models;
using SweetMoive.DAL;
using SweetMoive.DAL.ModelManage;
using SweetMoive.DAL.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SweetMoive.Areas.MovieUser.Controllers
{
    public class UserController : Controller
    {
        MovieManage movieManage = new MovieManage();      
        UserManage userManage = new UserManage();
        FavoriteManage favoriteManage = new FavoriteManage();
        HistoryManage historyManage = new HistoryManage();
        LikeManage likeMange = new LikeManage();
        FollowerManage followerMange = new FollowerManage();
        CommentManage commentMange = new CommentManage();
        ArticleManage articleMange = new ArticleManage();
        [UserAuthorize]
        public ActionResult Index()
        {
            var _user = userManage.Find(Convert.ToInt32(Session["UserID"]));
            return View(new UserViewModel {
                ID=_user.ID,
                UserName=_user.Username,
                Sex=_user.Sex.ToString(),
                Mymottoy=_user.MyMotto,
                Role=_user.Role.ToString(),
                SweetScore=_user.SweetScore
            });
        }
        [HttpGet]
        public ActionResult MyFavorite(int? id,int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _fav = favoriteManage.FindList(p => p.UserID == id);
            _fav = _fav.OrderBy(p => p.ID);
            const int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(_fav.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult EditUserInfo(int id)
        {
            var _user = userManage.Find(id);
            return PartialView(new EditUserViewModel {
                ID=_user.ID,
                Name=_user.Name,
                Sex=_user.Sex,
                Mottoy=_user.MyMotto,
                DefalutImgUrl=_user.DefaultImgUrl
            });
        }
        [HttpPost]
        public ActionResult isLike(int? id,int? userID)
        {
            // status[0:未点赞;1:已点赞;2:用户未登录]
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (userID == 0)
            {
                return Json(new { status = 2 });
            }
            var likecount = likeMange.Count(p => p.MovieCommentID == id && p.UserID == userID);
            if (likecount != 0)
            {
                return Json(new { status = 1 });
            }
            else
            {
                return Json(new { status = 0 });
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserInfo([Bind(Include = "ID,DefaultImgUrl,Name,Mottoy,Sex")]EditUserViewModel edituserViewModel,HttpPostedFileBase userImg)
        {
            Response _resp = new Response();
            var _user = userManage.Find(edituserViewModel.ID);
            var DefaultImg = "/DefaultImg/" + edituserViewModel.ID + ".jpg";
            _user.DefaultImgUrl= DefaultImg;
            if (ModelState.IsValid)
            {
                _user.MyMotto = edituserViewModel.Mottoy;
                _user.Name = edituserViewModel.Name;
                _user.Sex = edituserViewModel.Sex;
                _resp = userManage.Update(_user);
                if (_resp.Code == 1)
                {
                    _resp.Message = "用户信息填写成功！";
                }
                else
                {
                    _resp.Message = "信息上传失败，请重新尝试！";
                }
            }
            else
            {
                _resp.Code = 0;
                _resp.Message = General.GetModelErrorString(ModelState);
            }
            return Json(_resp);
        }
        [UserAuthorize]
        [HttpPost]
        public ActionResult Favorite(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _movie = movieManage.Find(id);
            if (_movie.Hidden == Movie.Hiddens.隐藏 || _movie == null)
            {
                return HttpNotFound();
            }
            var _user = userManage.Find(Convert.ToInt32(Session["UserID"]));
            var MovieID = _movie.ID;
            //Status【0:收藏成功1:取消收藏】
            var _fav = favoriteManage.Find(id, _user.ID);
            if (_fav==null)
            {
                Favorite _favor = new Favorite();
                _favor.MovieID = id;
                _favor.UserID = _user.ID;
                var _resp = favoriteManage.Add(_favor);
                return Json(new { StatusCode = 0 });
            }
            else
            {
                var _resp = favoriteManage.Delete(_fav.ID);
                return Json(new { StatusCode = 1 });
            }
        }
        [HttpPost]
        [UserAuthorize]
        public ActionResult Follower(int userID,int FollowerID)
        {
            var _follo = followerMange.Find(userID, FollowerID);
            if (_follo == null)
            {
                Follower _fow = new Follower();
                _fow.UserID = userID;
                _fow.Followed_user = FollowerID;
                var _resp = followerMange.Add(_fow);
                return Json(new { StatusCode = 1 });
            }
            else
            {
                var _resp = followerMange.Delete(_follo.ID);
                return Json(new { StatusCode = 0 });
            }
        }
        [HttpPost]
        [UserAuthorize]
        public ActionResult Likes(int userID,int commentID)
        {
            var _like = likeMange.Find(userID, commentID);
            var _comment = commentMange.Find(commentID);
            var _user = userManage.Find(_comment.UserID);
            if (_like == null)
            {
                Like like = new Like();
                like.UserID = userID;
                like.MovieCommentID = commentID;
                _comment.Likes = _comment.Likes++;
                _user.SweetScore = _user.SweetScore++;
                var _resp = likeMange.Add(like);
                var _res = commentMange.Update(_comment);
                var _re = userManage.Update(_user);
                return Json(new { StatusCode = 1 });
            }
            else
            {
                _comment.Likes = _comment.Likes--;
                _user.SweetScore = _user.SweetScore--;
                var _res = commentMange.Update(_comment);
                var _re = userManage.Update(_user);
                var _resp = likeMange.Delete(_like.ID);
                return Json(new { StatusCode = 0 });
            }
        }
        [HttpGet]
        public ActionResult MyHistory(int? id,int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _his = historyManage.FindList(p => p.UserID == id);
            _his = _his.OrderByDescending(p => p.ViewTime);
            const int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(_his.ToPagedList(pageNumber,pageSize));
        }
        [HttpPost]
        [UserAuthorize]
        public ActionResult DeleteHistory(int id)
        {
            var _his = historyManage.Find(id);
            historyManage.Delete(id);
            return Json(new { success = 1 });
            
        }
        [HttpGet]
        [UserAuthorize]
        public ActionResult Myfork(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _fork = followerMange.FindList(p => p.UserID == id).ToList();
            List<User> _user = new List<User>();
            foreach(var item in _fork)
            {
                var _follower = userManage.Find(p => p.ID == item.Followed_user);
                _user.Add(_follower);
            }
            return View(_user);
        }
        [HttpGet]
        public ActionResult OtherUser(int id)
        {
            var _user = userManage.Find(id);
            if (Session["UserID"] != null)
            {
                var userID = Convert.ToInt32(Session["UserID"]);
                int count = followerMange.Count(p => p.UserID == userID && p.Followed_user == id);
                if (count == 0)
                {
                    ViewBag.isFollower = false;
                }
                else
                {
                    ViewBag.isFollower = true;
                }
            }
            else
            {
                ViewBag.isFollower = false;
            }
            return View(new UserViewModel {
                ID=_user.ID,
                UserName=_user.Username,
                Mymottoy=_user.MyMotto,
                Name=_user.Name,
                Sex=_user.Sex.ToString(),
                Role=_user.Role.ToString()
            });
        }
        [HttpPost]
        public ActionResult Role(int id)
        {
            var _user = userManage.Find(id);
            if (_user.SweetScore >= 60)
            {
                if (_user.Role.ToString() == "普通用户")
                {
                    _user.Role = DAL.Models.User.Roles.评论专家;
                    var _resp = userManage.Update(_user);
                    return Json(new { success = 1 });
                }
                else
                {
                    return Json(new { success = 2 });
                }
            }
            else
            {
                return Json(new { success = 0 });
            }
        }
        [HttpGet]
        public ActionResult MyArticle(int id, int? page)
        {

SweetMoive/Areas/MovieUser/Views/Comment/CommentList.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<SweetMoive.DAL.Models.MovieComment>

@{ 
    ViewBag.Title = "CommentList";
    Layout = null;
}
@{int UserID; }
@if (Session["UserID"] == null)
            {
   UserID= 0;
}
else
{
    UserID= Convert.ToInt32(Session["UserID"]);
            }

<style>
    span.like-count {
        display:block;
        width:20px;
        height:20px;
    background: url("/Images/like.png") no-repeat 4px 6px;
}
span.like-count:hover {
     display:block;
        width:20px;
        height:20px;
    background: url("/Images/like.png") no-repeat 4px -24px;
    color: #395996;
}
</style>
<ul class="uk-comment-list">
    @foreach (var item in Model)
    {
        var score = item.Score / 2;
        <li>
            <article class="uk-comment">
                <header class="uk-comment-header uk-grid-medium uk-flex-middle" uk-grid>
                    <div class="uk-width-auto">
                        <img class="uk-comment-avatar" src="@item.User.DefaultImgUrl" width="80" height="80" alt="@item.UserID">
                    </div>
                    <div class="uk-width-expand">
                        <h4 class="uk-comment-title uk-margin-remove" style="color:#fff;" ><a class="uk-link-reset" href="#">@item.User.Username</a></h4>
                        <ul class="uk-comment-meta uk-subnav uk-subnav-divider uk-margin-remove-top">
                            <li><a href="#">@item.CommentTime</a></li>
                            <li>
                                对&nbsp;<a href="#">@item.Movie.MovieName</a>
                                &nbsp;评分：<div class="comment-rating" data-rating="@score"></div>
                              
                                <span class="like-count" data-id="@item.ID"></span>
                            </li>
                        </ul>
                    </div>
                </header>
                <div class="uk-comment-body">
                    <p>@item.Content</p>
                </div>
            </article>
        </li>
        <hr class="uk-divider-icon">
        <script>
          
            $.ajax({
                type: "POST",
                url: '@Url.Action("isLike","User")',
                dataType: "json",
                data:{id:@item.ID,userID:@UserID},
                success: function (result) {
                    if (result.status==2) {
                        return;
                    }
                    else if(result.status==1){
                        $('.like-count').css({"background":"url('/Images/like.png') no-repeat 4px -24px","color":"#395996"});
                    }else{
                        $('.like-count').css("background","url('/Images/like.png') no-repeat 4px 6px");
                    }
                },
                error:function(){
                    console.log("未知错误");
                }
            });
        </script>
    }
    
</ul>
<p>
    @Html.PagedListPager(Model,page=>Url.Action("CommentList","Comment",new { id=Model.First().MovieID,page=page}),PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() { HttpMethod="GET",UpdateTargetId="CommentList"}))
</p>
<script>
    $(".comment-rating").starRating({
        totalStars: 5,
        starShape: 'rounded',
        starSize: 16,
        emptyColor: 'lightgray',
        hoverColor: 'salmon',
        activeColor: 'crimson',
        useGradient: false,
        readOnly: true,
        forceRoundUp: true
    });
    $(function(){
        $(".like-count").on('click',function(){
            var id = $(this).attr("data-id");
            var userID=@UserID;
            if(userID==0){
                alert("未登录无法点赞！");
                return;
            }else{
                $.ajax({
                    type:"POST",
                    url:'@Url.Action("Likes","User")',
                    data:{userID:@UserID,commentID:id},
                    success:function(result){
                        if(result.StatusCode==0){
                            $(this).css("background","url('Images/like.png') no-repeat 4px 6px");
                        }else{
                            $(this).css({"background":"url('Images/like.png') no-repeat 4px -24px","color":"#395996"});

                        }
                    }
                });
            }
        });
    });
</script>