SweetMoive/Areas/AdminPerson/Controllers/HomeController.cs
using SweetMoive.DAL.ModelManage;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SweetMoive.Areas.AdminPerson.Controllers
{
    [AdminAuthorize]
    public class HomeController : Controller
    {
        [HttpGet]
        // GET: AdminPerson/Home
        public ActionResult Index()
        {
            ArticleManage _article = new ArticleManage();
            ViewBag.CommentNum = new CommentManage().Count();
            ViewBag.UserNum = new UserManage().Count();
            ViewBag.MovieNum = new MovieManage().Count();
            ViewBag.ArticleNum = _article.Count();
            List<DateTime> SevenDay = new List<DateTime>();
            List<int> Counts = new List<int>();
            for(var i = -6; i < 1; i++)
            {
                SevenDay.Add(DateTime.Now.Date.AddDays(i));
            }
            foreach(var item in SevenDay)
            {
                Counts.Add(_article.Count(p => p.Releasetime == item.Date));
            }
            ViewBag.labels = SevenDay.ToArray();
            ViewBag.data = Counts.ToArray();
            return View();
        }
    }
}

SweetMoive/Areas/MovieUser/Controllers/ArticleController.cs
using SweetMoive.Areas.MovieUser.Models;
using SweetMoive.DAL.ModelManage;
using SweetMoive.DAL.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SweetMoive.Areas.MovieUser.Controllers
{
    public class ArticleController : Controller
    {
        ArticleManage articleManage = new ArticleManage();
        [HttpGet]
        public ActionResult Index()
        {
            var _atr = articleManage.FindList();
            return View(_atr.ToList());
        }
        [HttpGet]
        public ActionResult ArticleDetail(int ID)
        {
            var _article = articleManage.Find(ID);
            return View(_article);
        }
        [HttpGet]
        public ActionResult ArticleSubmit()
        {
            var _movies = new MovieManage().FindList();
            List<SelectListItem> _movielistItems = new List<SelectListItem>(_movies.Count());
            foreach (var _movie in _movies)
            {
                _movielistItems.Add(new SelectListItem() { Text = _movie.MovieName, Value = _movie.ID.ToString() });
            }
            ViewBag.Movies = _movielistItems;
            return View();
        }
        [HttpPost]
        [UserAuthorize]
        [ValidateInput(false)]
        public ActionResult ArticleSubmit(AddArticleViewModel addarticleViewModel,HttpPostedFileBase banner,int UserID)
        {
            var MaxId = articleManage.ArticleId(p => p.ID);
            var articleID = MaxId + 1;
            if (banner != null)
            {
                var bannerName = Path.Combine(Request.MapPath("/ArticleImg"), articleID + ".jpg");
                if (System.IO.File.Exists(bannerName))
                {
                    System.IO.File.Delete(bannerName);
                }
                banner.SaveAs(bannerName);
            }
            if (ModelState.IsValid)
            {
                Article article = new Article();
                article.MovieID = addarticleViewModel.MovieID;
                article.Title = addarticleViewModel.Title;
                article.UserID = UserID;
                article.Content = addarticleViewModel.Content;
                article.Releasetime = DateTime.Now;
                article.Auditstatus = Article.Status.待审核;
                var _resp = articleManage.Add(article);
                return RedirectToAction("Index", "User");
            }
            else
            {
                return View(addarticleViewModel);
            }
        }
    }
}

SweetMoive/Areas/MovieUser/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net;
using SweetMoive.DAL.ModelManage;
using SweetMoive.DAL.Models;

namespace SweetMoive.Areas.MovieUser.Controllers
{
    public class CommentController : Controller
    {
        UserManage userManage = new UserManage();
        CommentManage commentMange = new CommentManage();
        LikeManage likeManage = new LikeManage();
        [HttpGet]
        public ActionResult CommentList(int? id,int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _comment = commentMange.FindList(p => p.MovieID == id);
            _comment=_comment.OrderBy(p => p.CommentTime);
            const int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(_comment.ToPagedList(pageNumber,pageSize));
        }
        //[HttpPost]
        //[UserAuthorize]
        //public ActionResult CommentLike(int)
        //{

        //    return Json(new { likestatus=1});
        //}
        [UserAuthorize]
        [HttpPost,ValidateAntiForgeryToken]
        public ActionResult CommentSubmit([Bind(Include ="ID,Content,score,UserID,MovieID")] MovieComment comment)
        {
            comment.CommentTime = DateTime.Now;

            comment.User = userManage.Find(comment.UserID);
            int isUser=commentMange.Count(p => p.UserID == comment.UserID&&p.MovieID==comment.MovieID);
            if (isUser > 0)
            {
                return Content("<h1 class='text-center' style='color:#fff;'>您已评论过此电影!</h1>");
            }
            if (ModelState.IsValid)
            {
                commentMange.Add(comment);
                comment.User.SweetScore = comment.User.SweetScore++;
                userManage.Update(comment.User);
                var _comment = commentMange.FindList(p => p.MovieID == comment.MovieID);
                _comment = _comment.OrderBy(p => p.CommentTime);
                const int pageSize = 5;
                return PartialView("CommentList", _comment.ToPagedList(1, pageSize));
            }
            return Content("<h1 class='text-center' style='color:#fff;'>评论失败</h1>");
        }
    }
}

SweetMoive/Areas/MovieUser/Controllers/UserController.cs
using PagedList;
using SweetMoive.Areas.MovieUser.Models;
using SweetMoive.DAL;
using SweetMoive.DAL.ModelManage;
using SweetMoive.DAL.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SweetMoive.Areas.MovieUser.Controllers
{
    public class UserController : Controller
    {
        MovieManage movieManage = new MovieManage();      
        UserManage userManage = new UserManage();
        FavoriteManage favoriteManage = new FavoriteManage();
        HistoryManage historyManage = new HistoryManage();
        LikeManage likeMange = new LikeManage();
        FollowerManage followerMange = new FollowerManage();
        CommentManage commentMange = new CommentManage();
        ArticleManage articleMange = new ArticleManage();
        [UserAuthorize]
        public ActionResult Index()
        {
            var _user = userManage.Find(Convert.ToInt32(Session["UserID"]));
            return View(new UserViewModel {
                ID=_user.ID,
                UserName=_user.Username,
                Sex=_user.Sex.ToString(),
                Mymottoy=_user.MyMotto,
                Role=_user.Role.ToString(),
                SweetScore=_user.SweetScore
            });
        }
        [HttpGet]
        public ActionResult MyFavorite(int? id,int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _fav = favoriteManage.FindList(p => p.UserID == id);
            _fav = _fav.OrderBy(p => p.ID);
            const int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(_fav.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult EditUserInfo(int id)
        {
            var _user = userManage.Find(id);
            return PartialView(new EditUserViewModel {
                ID=_user.ID,
                Name=_user.Name,
                Sex=_user.Sex,
                Mottoy=_user.MyMotto,
                DefalutImgUrl=_user.DefaultImgUrl
            });
        }
        [HttpPost]
        public ActionResult isLike(int? id,int? userID)
        {
            // status[0:未点赞;1:已点赞;2:用户未登录]
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (userID == 0)
            {
                return Json(new { status = 2 });
            }
            var likecount = likeMange.Count(p => p.MovieCommentID == id && p.UserID == userID);
            if (likecount != 0)
            {
                return Json(new { status = 1 });
            }
            else
            {
                return Json(new { status = 0 });
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUserInfo([Bind(Include = "ID,DefaultImgUrl,Name,Mottoy,Sex")]EditUserViewModel edituserViewModel,HttpPostedFileBase userImg)
        {
            Response _resp = new Response();
            var _user = userManage.Find(edituserViewModel.ID);
            var DefaultImg = "/DefaultImg/" + edituserViewModel.ID + ".jpg";
            _user.DefaultImgUrl= DefaultImg;
            if (ModelState.IsValid)
            {
                _user.MyMotto = edituserViewModel.Mottoy;
                _user.Name = edituserViewModel.Name;
                _user.Sex = edituserViewModel.Sex;
                _resp = userManage.Update(_user);
                if (_resp.Code == 1)
                {
                    _resp.Message = "用户信息填写成功！";
                }
                else
                {
                    _resp.Message = "信息上传失败，请重新尝试！";
                }
            }
            else
            {
                _resp.Code = 0;
                _resp.Message = General.GetModelErrorString(ModelState);
            }
            return Json(_resp);
        }
        [UserAuthorize]
        [HttpPost]
        public ActionResult Favorite(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _movie = movieManage.Find(id);
            if (_movie.Hidden == Movie.Hiddens.隐藏 || _movie == null)
            {
                return HttpNotFound();
            }
            var _user = userManage.Find(Convert.ToInt32(Session["UserID"]));
            var MovieID = _movie.ID;
            //Status【0:收藏成功1:取消收藏】
            var _fav = favoriteManage.Find(id, _user.ID);
            if (_fav==null)
            {
                Favorite _favor = new Favorite();
                _favor.MovieID = id;
                _favor.UserID = _user.ID;
                var _resp = favoriteManage.Add(_favor);
                return Json(new { StatusCode = 0 });
            }
            else
            {
                var _resp = favoriteManage.Delete(_fav.ID);
                return Json(new { StatusCode = 1 });
            }
        }
        [HttpPost]
        [UserAuthorize]
        public ActionResult Follower(int userID,int FollowerID)
        {
            var _follo = followerMange.Find(userID, FollowerID);
            if (_follo == null)
            {
                Follower _fow = new Follower();
                _fow.UserID = userID;
                _fow.Followed_user = FollowerID;
                var _resp = followerMange.Add(_fow);
                return Json(new { StatusCode = 1 });
            }
            else
            {
                var _resp = followerMange.Delete(_follo.ID);
                return Json(new { StatusCode = 0 });
            }
        }
        [HttpPost]
        [UserAuthorize]
        public ActionResult Likes(int userID,int commentID)
        {
            var _like = likeMange.Find(userID, commentID);
            var _comment = commentMange.Find(commentID);
            var _user = userManage.Find(_comment.UserID);
            if (_like == null)
            {
                Like like = new Like();
                like.UserID = userID;
                like.MovieCommentID = commentID;
                _comment.Likes = _comment.Likes++;
                _user.SweetScore = _user.SweetScore++;
                var _resp = likeMange.Add(like);
                var _res = commentMange.Update(_comment);
                var _re = userManage.Update(_user);
                return Json(new { StatusCode = 1 });
            }
            else
            {
                _comment.Likes = _comment.Likes--;
                _user.SweetScore = _user.SweetScore--;
                var _res = commentMange.Update(_comment);
                var _re = userManage.Update(_user);
                var _resp = likeMange.Delete(_like.ID);
                return Json(new { StatusCode = 0 });
            }
        }
        [HttpGet]
        public ActionResult MyHistory(int? id,int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _his = historyManage.FindList(p => p.UserID == id);
            _his = _his.OrderByDescending(p => p.ViewTime);
            const int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(_his.ToPagedList(pageNumber,pageSize));
        }
        [HttpPost]
        [UserAuthorize]
        public ActionResult DeleteHistory(int id)
        {
            var _his = historyManage.Find(id);
            historyManage.Delete(id);
            return Json(new { success = 1 });
            
        }
        [HttpGet]
        [UserAuthorize]
        public ActionResult Myfork(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var _fork = followerMange.FindList(p => p.UserID == id).ToList();
            List<User> _user = new List<User>();
            foreach(var item in _fork)
            {
                var _follower = userManage.Find(p => p.ID == item.Followed_user);
                _user.Add(_follower);
            }
            return View(_user);
        }
        [HttpGet]
        public ActionResult OtherUser(int id)
        {
            var _user = userManage.Find(id);
            if (Session["UserID"] != null)
            {
                var userID = Convert.ToInt32(Session["UserID"]);
                int count = followerMange.Count(p => p.UserID == userID && p.Followed_user == id);
                if (count == 0)
                {
                    ViewBag.isFollower = false;
                }
                else
                {
                    ViewBag.isFollower = true;
                }
            }
            else
            {
                ViewBag.isFollower = false;
            }
            return View(new UserViewModel {
                ID=_user.ID,
                UserName=_user.Username,
                Mymottoy=_user.MyMotto,
                Name=_user.Name,
                Sex=_user.Sex.ToString(),
                Role=_user.Role.ToString()
            });
        }
        [HttpPost]
        public ActionResult Role(int id)
        {
            var _user = userManage.Find(id);
            if (_user.SweetScore >= 60)
            {
                if (_user.Role.ToString() == "普通用户")
                {
                    _user.Role = DAL.Models.User.Roles.评论专家;
                    var _resp = userManage.Update(_user);
                    return Json(new { success = 1 });
                }
                else
                {
                    return Json(new { success = 2 });
                }
            }
            else
            {
                return Json(new { success = 0 });
            }
        }
        [HttpGet]
        public ActionResult MyArticle(int id, int? page)
        {

SweetMoive/Areas/AdminPerson/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">仪表盘</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-comments fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@ViewBag.CommentNum</div>
                        <div>总评论数量</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","Comment")">
                <div class="panel-footer">
                    <span class="pull-left">查看详情</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@ViewBag.UserNum</div>
                        <div>总用户数量</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","User")">
                <div class="panel-footer">
                    <span class="pull-left">查看详情</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-youtube-play fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@ViewBag.MovieNum</div>
                        <div>总电影数量</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","Movie")">
                <div class="panel-footer">
                    <span class="pull-left">查看详情</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-book fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">@ViewBag.ArticleNum</div>
                        <div>总文章数量</div>
                    </div>
                </div>
            </div>
            <a href="@Url.Action("Index","Article")">
                <div class="panel-footer">
                    <span class="pull-left">查看详情</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-offset-1 col-lg-10">
        <canvas id="myChart"></canvas>
    </div>
</div>
@Scripts.Render("~/bundles/chart")
@section scripts{
    <script>
        window.onload = function () {
            var ctx = document.getElementById('myChart').getContext('2d');
            window.myLine = new Chart(ctx, config);
        };
        var labelAry=new Array();
        var dataAry=new Array();
        var data2=@Html.Raw(Json.Encode(ViewBag.data));
        var myDate = new Date(); //获取今天日期
        myDate.setDate(myDate.getDate() - 7);
        var dateArray = []; 
        var dateTemp; 
        var flag = 1; 
        for (var i = 0; i < 7; i++) {
            dateTemp = (myDate.getMonth()+1)+"-"+(myDate.getDate()+1);
            dateArray.push(dateTemp);
            myDate.setDate(myDate.getDate() + flag);
        }
        for(var i=0;i<data2.length;i++){
            dataAry[i]=data2[i];
        }
        var config = {
            type: 'line',
            data: {
                labels:dateArray,
                datasets:[{
                    label:'文章提交量',
                    backgroundColor: 'rgb(240,248,255)',
                    borderColor: 'rgb(65,105,225)',
                    data:dataAry,
                    fill:false,
                }]
            },
            options: {
                responsive: true,
                title: {
                    display: true,
                    text: '每日文章提交量统计'
                },
                tooltips: {
                    mode: 'index',
                    intersect: false,
                },
                hover: {
                    mode: 'nearest',
                    intersect: true
                },
                scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: '日期'
                        }
                    }],
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: '总数'
                        }
                    }]
                }
            }
        }
        </script>
}